---
- name: Copy all files and directories
  become: true
  ansible.posix.synchronize:
    src: "{{ home_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
      # - "--exclude=.git/"
      - --exclude=.gitignore
      - --exclude=README.md
      - --exclude=ansible/
      - --exclude=venv/

- name: Create main directory structure
  ansible.builtin.file:
    path: "{{ dest_dir }}"
    state: directory
    mode: "0755"
