- name: copy all files and directories
  become: true 
  synchronize:
    src: "{{ home_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
      # - "--exclude=.git/"
      - "--exclude=.gitignore"
      - "--exclude=README.md"
      - "--exclude=ansible/"
      - "--exclude=venv/"

- name: create main directory structure 
  ansible.builtin.file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'