- name: make sure the old secret file is absent
  become: true
  ansible.builtin.file:
    path: "{{home_dir}}/secrets/{{ secret_file }}"
    state: absent
  delegate_to : localhost

- name: wait for secret file to get generated
  wait_for:
    timeout: "{{timeout}}"

- name: fetch the secret file to control node
  become: true
  fetch:
    src: "{{ secret_dir }}/{{ secret_file }}"
    dest: "{{home_dir}}/secrets/{{ secret_file }}"
    flat: yes
    fail_on_missing: true

- name : Print at the secret file path
  debug:
    msg: "You can now see Vault secrets at `{{home_dir}}/secrets/{{ secret_file }}`"