- name: deploy boundary compose file
  become: true
  shell: docker rm -f boundary_db boundary && rm -rf /srv/boundary && VAULT_ADDR={{ vault_addr }} docker compose -f "{{ compose_file }}/boundary.yml" up -d
  register: output
  ignore_errors: true

- name : run terraform configuration
  shell: HOME_DIR={{ home_dir }} BOUNDARY_ADDR={{ boundary_addr }} bash "{{home_dir}}/scripts/init.sh" boundary
  delegate_to: localhost