- name : create hcp external
  become: true
  docker_network:
    name: "hashicorp"

# - name: deploy the docker compose files
#   become: true
#   community.docker.docker_compose:
#     project_src: "{{ compose_file }}"
#     build: false
#   register: output

- name: Get a list of Docker containers
  community.docker.docker_container_info:
    name : "{{ item }}"
  loop : 
    - "{{ containers }}"
  register: containers_info

- name: Remove vault containers if exists.
  community.docker.docker_container: 
    name : "{{  item.container.Id  }}"
    state: absent
    force_kill: yes     
  loop :
    - "{{ containers_info.results }}"
  when : item.exists 

- name: deploy vault using deploy_script
  become: true
  shell: bash {{ deploy_script }} vault
  register: output