---
- name: Check the status of docker images jobs
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/docker_pull_status.yml"

- name: deploy vault 
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/deploy.yml"

- name: retrieve vault secrets
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/secrets.yml"
