---
- name: Make sure the old secret file is absent
  become: true
  ansible.builtin.file:
    path: "{{ home_dir }}/secrets/{{ secret_file }}"
    state: absent
  delegate_to: localhost

- name: Wait for secret file to get generated
  ansible.builtin.wait_for:
    timeout: 10

- name: Fetch the secret file to control node
  become: true
  ansible.builtin.fetch:
    src: "{{ secret_dir }}/{{ secret_file }}"
    dest: "{{ home_dir }}/secrets/{{ secret_file }}"
    flat: true
    fail_on_missing: true

- name: Print at the secret file path
  ansible.builtin.debug:
    msg: You can now see Vault secrets at `{{ home_dir }}/secrets/{{ secret_file }}`
