- name: fetch the secret file to control node
  become: true
  fetch:
    src: "{{stack_dir}}/secrets/secrets.txt"
    dest: "{{home_dir}}/secrets/secrets.txt"
    flat: yes
    fail_on_missing: true

- name : Print at the secret file path
  debug:
    msg: "You can now see Vault secrets at `{{home_dir}}/secrets/secrets.txt`"