- name: Slurp secret file content
  slurp:
    src: "{{ secret_file }}"
  register: secrets

- name: Display secrets
  debug:
    msg: "{{ secrets.['content'] | b64decode }}"

- name: Remove the secrets.txt file form the target node(s)
  ansible.builtin.file:
    path: "{{ secret_file }}"
    state: absent